2-3 point opening:
  description: 'User-defined preset: 2-3 point opening'
  global_labels:
    tenuki_ok: true
  move_labels:
    play_gote: true
    joseki: true
    profit_viable: true
    gote: true
    profit_move: true
    play_empty_corner: true
    initiative:gote: true
    shape:joseki: true
    strategic:profit_move: true
    tactical:play_empty_corner: true
4-4 point opening:
  description: 'User-defined preset: 4-4 point opening'
  global_labels:
    tenuki_ok: true
  move_labels:
    initiative:gote: true
    strategic:influence_move: true
    tactical:play_empty_corner: true
    shape:joseki: true
keima apperoach 4-4:
  description: 'User-defined preset: keima apperoach 4-4'
  global_labels:
    tenuki_ok: true
  move_labels:
    initiative:gote: true
    stress_area:right_side: true
    reduce_area:lower_side: true
    reduce_area:br_corner: true
    shape:joseki: true
    strategic:fight_move: true
    strategic:reduction_move: true
    strategic:building_move: true
    tactical:approach_opp_corner: true
3-3 invasion:
  description: 'User-defined preset: 3-3 invasion'
  global_labels:
    tenuki_ok: true
  move_labels:
    initiative:gote: true
    shape:joseki: true
    strategic:profit_move: true
    strategic:invasion_move: true
    tactical:inside_opp_corner: true
descend vs 3-3:
  description: 'User-defined preset: descend vs 3-3'
  global_labels:
    urgent_local: true
  move_labels:
    initiative:sente: true
    stress_area:left_side: true
    reduce_area:lower_side: true
    shape:joseki: true
    shape:descend: true
    strategic:influence_move: true
    strategic:fight_move: true
    tactical:capture_race: true
extend from 3-3:
  description: 'User-defined preset: extend from 3-3'
  global_labels:
    urgent_local: true
  move_labels:
    initiative:sente: true
    stress_area:left_side: true
    reduce_area:bl_corner: true
    shape:joseki: true
    shape:extension: true
    strategic:must_live_move: true
    strategic:profit_move: true
    tactical:extend_side: true
    tactical:get_base: true
