2-3 point opening:
  description: 'User-defined preset: 2-3 point opening'
  global_labels:
    tenuki_ok: true
  move_labels:
    play_gote: true
    joseki: true
    profit_viable: true
    gote: true
    profit_move: true
    play_empty_corner: true
    initiative:gote: true
    shape:joseki: true
    strategic:profit_move: true
    tactical:play_empty_corner: true
    move_attributes:big_move: true
    move_attributes:low_move: true
    stress_area:lower_side: true
    stress_area:bl_corner: true
    reduce_area:br_corner: true
    reduce_area:right_side: true
4-4 point opening:
  description: 'User-defined preset: 4-4 point opening'
  global_labels:
    tenuki_ok: true
  move_labels:
    initiative:gote: true
    strategic:influence_move: true
    tactical:play_empty_corner: true
    shape:joseki: true
    stress_area:center: true
    move_attributes:high_move: true
    move_attributes:big_move: true
    move_attributes:fast_move: true
3-3 invasion:
  description: 'User-defined preset: 3-3 invasion'
  global_labels:
    tenuki_ok: true
  move_labels:
    initiative:gote: true
    move_attributes:low_move: true
    move_attributes:big_move: true
    strategic:profit_move: true
    strategic:reduction_move: true
    strategic:invasion_move: true
    tactical:inside_opp_corner: true
descend vs 3-3:
  description: 'User-defined preset: descend vs 3-3'
  global_labels:
    urgent_local: true
  move_labels:
    initiative:sente: true
    move_attributes:good_shape: true
    move_attributes:high_move: true
    move_attributes:thick_move: true
    move_attributes:big_move: true
    strategic:fight_move: true
    strategic:influence_move: true
    tactical:seal_in: true
    tactical:joseki: true
    move_attributes:descend: true
extend from 3-3:
  description: 'User-defined preset: extend from 3-3'
  global_labels:
    urgent_local: true
  move_labels:
    initiative:sente: true
    move_attributes:good_shape: true
    move_attributes:low_move: true
    move_attributes:thick_move: true
    move_attributes:big_move: true
    move_attributes:extension: true
    strategic:must_live_move: true
    strategic:profit_move: true
    tactical:get_base: true
keima 4-4 approach:
  description: 'User-defined preset: keima 4-4 approach'
  global_labels:
    tenuki_ok: true
  move_labels:
    initiative:gote: true
    shape:joseki: true
    strategic:fight_move: true
    strategic:reduction_move: true
    strategic:building_move: true
    tactical:approach_opp_corner: true
    move_attributes:fast_move: true
    move_attributes:low_move: true
    move_attributes:big_move: true
keima vs 3-3 sente line:
  description: 'User-defined preset: keima vs 3-3 sente line'
  global_labels:
    tenuki_ok: true
  move_labels:
    initiative:sente: true
    move_attributes:fast_move: true
    move_attributes:thin_light_move: true
    move_attributes:good_shape: true
    move_attributes:big_move: true
    move_attributes:keima: true
    strategic:influence_move: true
    strategic:fight_move: true
    tactical:seal_in: true
    tactical:joseki: true
extend vs keima joseki 3-3:
  description: 'User-defined preset: extend vs keima joseki 3-3'
  global_labels:
    urgent_local: true
  move_labels:
    initiative:sente: true
    move_attributes:good_shape: true
    move_attributes:thick_move: true
    move_attributes:big_move: true
    move_attributes:extension: true
    strategic:must_live_move: true
    tactical:get_base: true
    tactical:joseki: true
2nd line vs keima sente vs 3-3:
  description: 'User-defined preset: 2nd line vs keima sente vs 3-3'
  global_labels:
    urgent_local: true
  move_labels:
    initiative:gote: true
    move_attributes:low_move: true
    move_attributes:thick_move: true
    move_attributes:big_move: true
    move_attributes:hane: true
    strategic:must_live_move: true
    strategic:profit_move: true
atari vs tenuki keima 3-3:
  description: 'User-defined preset: atari vs tenuki keima 3-3'
  global_labels:
    tenuki_ok: true
  move_labels:
    initiative:sente: true
    stress_area:right_side: true
    stress_area:tr_corner: true
    reduce_area:center: true
    move_attributes:slow_move: true
    move_attributes:big_move: true
    move_attributes:hane: true
    strategic:profit_move: true
    strategic:fight_move: true
    tactical:expand_while_reducing: true
    tactical:atari: true
    tactical:joseki: true
    tactical:make_heavy: true
long L connect vs atari:
  description: 'User-defined preset: long L connect vs atari'
  global_labels:
    urgent_local: true
  move_labels:
    initiative:gote: true
    stress_area:right_side: true
    stress_area:upper_side: true
    stress_area:center: true
    move_attributes:good_shape: true
    move_attributes:thick_move: true
    move_attributes:slow_move: true
    move_attributes:big_move: true
    strategic:influence_move: true
    tactical:connect: true
    tactical:wall: true
    tactical:joseki: true
    tactical:cut_available: true
