hoshi during opening:
  description: 'User-defined preset: hoshi during opening'
  global_labels:
    tenuki_ok: true
  move_labels:
    play_gote: true
    joseki: true
    profit_viable: true
    influence_viable: true
    enclose_own_corner: true
2-3 point opening:
  description: 'User-defined preset: 2-3 point opening'
  global_labels:
    tenuki_ok: true
  move_labels:
    play_gote: true
    joseki: true
    profit_viable: true
    enclose_own_corner: true
