tags:
  global:
    - {name: tenuki_ok,           desc: "Local urgency low; safe to play elsewhere"}
    - {name: urgent_local,        desc: "Local response required"}
  initiative:
    - {name: sente,    desc: "Follow-up opponent must answer"}
    - {name: gote,     desc: "Take points"}
  strategic:
    - {name: building_move,     desc: "Building moyo is viable"}
    - {name: influence_move,    desc: "Influence is viable"}
    - {name: profit_move,       desc: "Take profit"}
    - {name: invasion_move,     desc: "Inside enemy sphere can live/reduce"}
    - {name: reduction_move,    desc: "Should reduce from outside"}
    - {name: fight_move,        desc: "Starts a fight"}
    - {name: must_live_move,    desc: "Safety first"}
  tactical:
    - {name: approach_opp_corner,    desc: "Large-point move near a corner"}
    - {name: play_empty_corner,      desc: "Play in an empty corner"}
    - {name: enclose_own_corner,     desc: "Enclose a corner"}
    - {name: inside_opp_corner,      desc: "Invade opponent's corner"}
    - {name: seal_in,                desc: "Seal in opponent's group or threaten to"}
    - {name: expand_while_reducing,  desc: "Expand own territory while reducing opponent's"}
    - {name: connect,                desc: "Connect 2+ groups"}
    - {name: get_base,               desc: "Get base/make shape for weak group"}
    - {name: jump_into_center,       desc: "Jump into center with weak group"}
    - {name: throw_in,            desc: "Throw in center with weak group"}
    - {name: make_eyes,           desc: "Make eyespace"}
    - {name: steal_eyes,          desc: "Steal eyespace "}
    - {name: pincer,              desc: "Pincer attack"}
    - {name: cut_available,       desc: "Cut threatens to separate groups"}
    - {name: ladder_favourable,   desc: "There is a favourable ladder"}
    - {name: ladder_against,      desc: "There is an unfavourable ladder"}
    - {name: atari,               desc: "This move is an atari"}
    - {name: ko_threat,           desc: "Move threatens to win ko if ignored"}
    - {name: capture_race,        desc: "Semeai"}
    - {name: use_aji,             desc: "Use aji"}
    - {name: sacrifice,           desc: "Sacrificing a group"}
    - {name: leaning_attack,      desc: "Leaning attack"}
    - {name: splitting_attack,    desc: "Splitting attack"}
    - {name: ladder_breaker,      desc: "Ladder breaker"}
    - {name: make_heavy,          desc: "Make opponent's group heavy"}
    - {name: wall,                desc: "Wall"}
    - {name: tesuji,              desc: "Net, etc"}
    - {name: joseki,              desc: "Joseki"}
    - {name: tenuki,              desc: "Tenuki"}
  stress_area_both: 
    - {name: left_side,      desc: "Left side"}
    - {name: upper_side,     desc: "Upper side"}
    - {name: right_side,     desc: "Right side"}
    - {name: lower_side,     desc: "Lower side"}
    - {name: tl_corner,      desc: "Top left corner"}
    - {name: tr_corner,      desc: "Top right corner"}
    - {name: bl_corner,      desc: "Bottom left corner"}
    - {name: br_corner,      desc: "Bottom right corner"}
    - {name: center,         desc: "Center"}
  reduce_area_both:
    - {name: left_side,      desc: "Left side"}
    - {name: upper_side,     desc: "Upper side"}
    - {name: right_side,     desc: "Right side"}
    - {name: lower_side,     desc: "Lower side"}
    - {name: tl_corner,      desc: "Top left corner"}
    - {name: tr_corner,      desc: "Top right corner"}
    - {name: bl_corner,      desc: "Bottom left corner"}
    - {name: br_corner,      desc: "Bottom right corner"}
    - {name: center,         desc: "Center"}
  move_attributes:
    - {name: good_shape,     desc: "Play tiger's mouth, table, etc"}
    - {name: bad_shape,      desc: "Play weak shape move"}
    - {name: low_move,       desc: "Low move"}
    - {name: high_move,      desc: "High move"}
    - {name: thin_light_move,  desc: "Thin light move"}
    - {name: thick_move,     desc: "Thick move"}
    - {name: slow_move,      desc: "Slow move"}
    - {name: fast_move,      desc: "Fast move"}
    - {name: big_move,       desc: "Big move"}
    - {name: small_move,     desc: "Small move"}
    - {name: hane,           desc: "Hane"}
    - {name: extension,      desc: "Extend next to stone, horizontally"}
    - {name: descend,        desc: "Descend/Ascend, vertically"}
    - {name: keima,          desc: "Keima"}
    - {name: ogeima,         desc: "Ogeima"}
    - {name: attachment,     desc: "Attachment"}
    - {name: one_space_jump, desc: "One space jump"}
    - {name: two_space_jump, desc: "Two space jump"}
    - {name: shoulder_hit,   desc: "Shoulder hit"}
    - {name: capping_move,   desc: "Capping move"}
    - {name: peep,           desc: "Peeping move"}
    - {name: kosumi,         desc: "Kosumi"}
